#pragma once

#define OFF 0
#define ON 1

#define ENABLE_GUI 1
#define ENABLE_IPC 1
#define DATA_PATH "/opt/cathook/data"
#define ENABLE_VAC_BYPASS 1
#define ENABLE_TEXTMODE_STDIN 0
#define ENABLE_TEXTMODE 0
#define ENABLE_BINARYMODE 0
#define ENABLE_LOGGING 1
#define ENABLE_CLIP 1

#define ENABLE_VISUALS 1
#define ENABLE_GLEZ_DRAWING 0
#define ENABLE_ENGINE_DRAWING 0
#define ENABLE_IMGUI_DRAWING 1
#define EXTERNAL_DRAWING 0
#define ENFORCE_STREAM_SAFETY 0

#define UNITY_ZEROKERNEL 1
