#!/usr/bin/env bash

# Verify that we are root
if [ "$(id -u)" -ne 0 ]; then
  echo -e "\033[1;33m \n \nThis script must be run as root!\n\033[0m"
  exit 1
fi

# Determine the user running the script
[[ -n "$SUDO_USER" ]] && RUNUSER="$SUDO_USER" || RUNUSER="$LOGNAME"
RUNCMD="sudo -u $RUNUSER"



# Find the process ID of the game
line=$(pgrep -u "$RUNUSER" hl2_linux)
arr=($line)

if [ $# -eq 1 ]; then
  proc=$1
else
  if [ ${#arr[@]} -eq 0 ]; then
    echo "TF2 isn't running!"
    exit 1
  fi
  proc=${arr[0]}
fi

echo "Running instances: ${arr[@]}"
echo "Attaching to $proc"

FILENAME="/tmp/.gl$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 6)"

# Copy the shared library to a temporary location
cp "obj/bin/libcathook.so" "$FILENAME"

echo "Loading $FILENAME to $proc"

gdbbin="gdb"
$gdbbin -n -q -batch \
-ex "attach $proc" \
-ex "echo -e \033[1mCalling dlopen\033[0m\n" \
-ex "call ((void*(*)(const char*, int))dlopen)(\"$FILENAME\", 1)" \
-ex "echo -e \033[1mCalling dlerror\033[0m\n" \
-ex "call ((char*(*)(void))dlerror)()" \
-ex "detach" \
-ex "quit"

# Remove the temporary file
rm "$FILENAME"

echo
echo "Have fun pwning n00bs with cowhook!"
